import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout-components/footer/footer";
import Header from "@/components/layout-components/header/header";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
      <Header />
        {children}
      <Footer />
      </body>
      
    </html>
  );
}
